[package]
name = "simulator"
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
mousefood = { path = "../../mousefood/" }
embedded-graphics-simulator = "0.7"
ratatui = { workspace = true }
